Ros2 devel
ros/bond_core pull request #54
Opened 2019-07-25 00:40 UTC by Karsten1987

This is a continuation of #43 which hopefully some of the outstanding reviews addressed.

2019-08-06 15:31 UTC, mjcarroll requested changes
This looks like a straightforward port.  I know it's blocking for diagnostics, so it's probably okay to go out as is.

I do have some concern about prepending the apache license on some of these files, I'm not sure if that is valid behavior.

Also, potentially as an enhancement down the road, this should take advantage of lifecycle nodes, but that's probably not critical at this juncture.

2019-08-06 15:31 UTC, mjcarroll commented on bondcpp/include/bondcpp/BondSM_sm.hpp
> +// Copyright 2018 Open Source Robotics Foundation, Inc.
I don't know if prepending the license like this is valid?

2019-08-06 16:06 UTC, Karsten1987 commented
Oh yeah, I was raising my concerns about this as well but didn’t address it in this PR. I’ll revert them to their original license.

2019-08-06 22:15 UTC, Karsten1987 commented
https://github.com/ros/bond_core/pull/54/commits/71172695fe5c71063aaf5f05712545f7dab527d4 should remove the false declaration of Apache2.
I further disable the linter for copyright as a non-apache2 license currently doesn't match.

2019-08-12 18:12 UTC, Karsten1987 commented
@mjcarroll do you mind taking another look on this? 🙏

2019-08-13 17:28 UTC, mjcarroll approved these changes

2019-09-10 21:59 UTC, merged

2019-09-10 22:02 UTC, mjcarroll commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8105)](http://ci.ros2.org/job/ci_linux/8105/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4104)](http://ci.ros2.org/job/ci_linux-aarch64/4104/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6605)](http://ci.ros2.org/job/ci_osx/6605/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=7986)](http://ci.ros2.org/job/ci_windows/7986/)

2019-09-10 22:07 UTC, Karsten1987 commented
testing `smclib`, `bond`, `bondcpp`, `bond_core`, `test_bond`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8106)](http://ci.ros2.org/job/ci_linux/8106/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4105)](http://ci.ros2.org/job/ci_linux-aarch64/4105/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6606)](http://ci.ros2.org/job/ci_osx/6606/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=7987)](http://ci.ros2.org/job/ci_windows/7987/)