Lifecycle support 2
ros/bond_core pull request #67
Opened 2020-07-29 00:52 UTC by SteveMacenski

Supersedes https://github.com/ros/bond_core/pull/64 to:
- Enable lifecycle nodes in ROS2
- Fix ROS2 porting issues
- Fix ROS2 WaitUntilXYZ() functions with spins on nodes already spinning (requirement for this to work)
- Tested to be actualy working now & integrated into Nav2
- No reduced capability

2020-07-30 10:29 UTC, naiveHobo commented on bondcpp/src/bond.cpp
> -    rclcpp::spin_some(nh_);
This loop throws `terminate called after throwing an instance of 'statemap::StateUndefinedException'`. I fixed it locally by adding a `std::this_thread::sleep_for(100ms)`. I can't exactly understand why it throws that exception without the sleep call.

2020-07-30 17:41 UTC, SteveMacenski commented
Whoops, see the commit, I didn't push it to remote, I had already done that :-)

2020-08-06 00:41 UTC, SteveMacenski commented
Pinging @mjcarroll as listed maintainer, can we get a review?

This work has been merged in and used on nav2 for about a week now without any issues. I think this is safe for a review for inclusion

2020-08-20 16:53 UTC, SteveMacenski commented
Pinging @mjcarroll

2020-08-20 18:33 UTC, mjcarroll commented
Pong. I'm reviewing.

2020-08-21 14:30 UTC, mjcarroll requested changes
Overall, looks good, one comment about DRY and a question about a previous resolution.

2020-08-21 14:30 UTC, mjcarroll commented on bondcpp/include/bondcpp/bond.hpp
> +    const std::string & topic, const std::string & id,
I think it would make sense to make a constructor that takes the `node_interfaces`, and then both the `Node` and `LifecycleNode` variants could be delegating constructors, since it appears the implementation is the same.

2020-08-21 14:30 UTC, mjcarroll commented on bondcpp/src/bond.cpp
> -    rclcpp::spin_some(nh_);
@SteveMacenski What was the actual resolution on this?

2020-08-21 14:30 UTC, mjcarroll commented on bondcpp/src/bond.cpp
> +    if (timeout >= rclcpp::Duration(0.0 * 1e9)) {
Why multiply by 1e9?  Still zero, right?  I know you didn't add this, just seems weird.

2020-08-21 19:00 UTC, SteveMacenski commented on bondcpp/src/bond.cpp
> +    if (timeout >= rclcpp::Duration(0.0 * 1e9)) {
Agreed, I just didn't change it. I can remove it in the update

2020-08-21 19:03 UTC, SteveMacenski commented on bondcpp/include/bondcpp/bond.hpp
> +    const std::string & topic, const std::string & id,
The big reason was to later deal with `WeakPtr`s. Since we need to lock it before we're able to access things, we can't make that in a constructor form in the same way we we might in [CostmapSubscriber](https://github.com/ros-planning/navigation2/blob/main/nav2_costmap_2d/src/costmap_subscriber.cpp#L23). I'd be fine changing it to this now though. It's a "later" problem.

2020-08-21 19:04 UTC, SteveMacenski commented on bondcpp/src/bond.cpp
> -    rclcpp::spin_some(nh_);
Without some throttling the updates weren't being processed. The spin acted essentially as a time blocker and with it removed, we needed to replace it with something to slow the loop so it wouldn't be a `while true`

2020-08-21 19:14 UTC, SteveMacenski commented on bondcpp/include/bondcpp/bond.hpp
> +    const std::string & topic, const std::string & id,
While trying to implement it, I remember now why, I would otherwise need to pull out a bunch more interfaces and make things a bit more complex because of the parameters and subscribers that are in the constructors and how they interact with lifecycle vs normal nodes is a pain.

2020-08-21 19:14 UTC, SteveMacenski commented on bondcpp/src/bond.cpp
> +    if (timeout >= rclcpp::Duration(0.0 * 1e9)) {
Done

2020-08-21 19:16 UTC, SteveMacenski commented on bondcpp/include/bondcpp/bond.hpp
> +    const std::string & topic, const std::string & id,
Create publisher really wants a `NodeT`, or else I'd have to mess with allocators and other stuff that's really shouldn't be exposed here https://github.com/ros2/rclcpp/blob/81049c42c0b04d0cc80a3e4c3a0819a735e23cdc/rclcpp/include/rclcpp/create_publisher.hpp#L43

2020-08-23 22:36 UTC, ros-discourse commented
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2020-08-20/16063/1

2020-09-01 22:50 UTC, SteveMacenski commented
@mjcarroll pinging again

2020-09-01 23:49 UTC, mjcarroll approved these changes

2020-09-01 23:50 UTC, merged

2020-09-01 23:50 UTC, mjcarroll commented
@SteveMacenski would you like this to be released into rolling?

2020-09-02 18:11 UTC, SteveMacenski commented
I don't require it, but might be a good idea. If nothing else, having it in Foxy would be our immediate needs.